on:
    push:
        branches:
            - master

jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js 12.x
          uses: actions/setup-node@v3
          with:
            node-version: '12.x'
        - name: Build
          run: |
            yarn install
            yarn build
          env:
            REACT_APP_PIXABAY_KEY: ""
            REACT_APP_ICONSCOUT_SECRET: ""
            REACT_APP_ICONSCOUT_CLIENT_ID: ""
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
          # with:
            # personal_token: ${{ secrets.demo }}
            #publish_dir: ./dist
